admins: [1919745140] 

forwards:
  - source: -1001713025945
    dest: [-1001689961510,-1001775479387,-1001761089302]

plugins:
  filter:
    text:
      "RUN BANAKAR OUT": Run Banakar Out
      "CATCH OUT✔️✔️": 🚾 CATCH OUT 🚾
      "WIDE ✔️✔️" : 🎾 WIDE 🎾
      "RUN OUT✔️✔️": 🚾 RUN OUT 🚾
      "✔️✔️": " "
